the integrand function in the fqpck_wrapper.f90 is added f90_vs_numpy_arrays_5_qpck.f90 transformed to old style quadpack version given in John Burkardt fcython_qpck_1/quadpack.f90 (may be interfacing integrand function can help in a transforming qags subroutine to modern fortran style)
Current wrapping version is performed in a somewhat similar style as the test04() subroutine in fcython_qpck_1/f90_vs_numpy_arrays_5_qpck.f90

The following errors were arisen
~/rr4/fcython/fcython_qpck_1 $ make
gfortran -Wall -std=f2008 -Wextra -Wimplicit-interface -fPIC -g -fcheck=all -c fqpck_wrapper.f90
fqpck_wrapper.f90:11.37:

  subroutine c_quad(c_f, a, b, epsabs, epsrel, result, abserr, neval, ier) bind
                                     1
Error: Dummy 'epsabs' at (1) cannot have an initialiser
fqpck_wrapper.f90:11.45:

  subroutine c_quad(c_f, a, b, epsabs, epsrel, result, abserr, neval, ier) bind
                                             1
Error: Dummy 'epsrel' at (1) cannot have an initialiser
fqpck_wrapper.f90:21.16:

    call qags ( c_f, a, b, epsabs, epsrel, result, abserr, neval, ier )
                1
Error: Interface mismatch in dummy procedure 'f' at (1): Type/kind mismatch in return value of 'c_f'
make: *** [fqpck_wrapper.o] Error 1